#!/bin/bash
time=$(echo -e "How many minutes do you want to focus for?" | dmenu -i)
if [ $time = allow ]; then
	allowedprogram=$(echo -e "choose program to allow" | dmenu -i )
	allowedtime=$(echo -e "how many minutes?" | dmenu -i )
	let allowedtime=allowedtime\*60
	echo "$allowedtime" > ~/.config/scripts/allowlist/$allowedprogram

elif [ $time = setall ]; then
	allowedtime=$(echo -e "set all for how many minutes?" | dmenu -i )
	if [ $allowedtime -gt 0 ]; then
		let allowedtime=allowedtime\*60
	fi
	FILES=~/.config/scripts/allowlist/*
	for Program in $FILES
	do
		echo "$allowedtime" > $Files$Program
		notify-send "All programs time set to $allowedtime"
	done

elif [ $time = nuke ]; then
	FILES=~/.config/scripts/allowlist/*
	for Program in $FILES
	do
		echo "0" > $Files$Program
		notify-send "All programs time set to 0"
	done

else
	resource=$(echo -e "Birch\nBlaze\nCreamia\nCosmo\nCelestia\nChurch\nHollow\nLadyNimu\nMario\nMarisa\nNachure\nPooh\nShip\nSnow\nStella" | dmenu -i)
	#echo -e "time set for $time minutes!"
	let time=time\*60
	#echo out to file
	echo "$time" > ~/.config/scripts/allowlist/totaltime
	if [ $time -gt 0 ]
	then
		#set wallpaper and Xresources
		if [[ -f ~/.config/scripts/isfocusing ]]; then
			notify-send "resetting time"
		else
			#remember default wallpaper
			mv -f /home/blink/.config/wall.png /home/blink/.config/wallpaper/wall_Shallow.png
			touch ~/.config/scripts/isfocusing
		fi
		cp -f /home/blink/.config/wallpaper/wall_$resource.png /home/blink/.config/wall.png &&
		setbg &&
		xrdb /home/blink/.config/Xassets/X$resource &&
		i3-msg restart &&
		pkill -x --signal USR1 xst
		sleep 1 #so Xresources can refresh before booting up orgterm

		#start up orgterm if nothing is playing currently
		#if mpc status | grep playing
		#then
		#	notify-send "mpd is playing, enjoy your current music"
		#else
		#	if pgrep -cx orgterm
		#	then
		#		echo "org"
		#	else
		#		st orgterm ~/King\ Of\ A\ Cursed\ Throne.org
		#		disown
		#	fi
		#fi
		#if other instance is running, then don't run
		if [[ -f ~/.config/scripts/isfocusing ]]; then
			#sleep and check for unallowed programs
			while [[ $time -gt 0 ]]
			do
				~/.config/scripts/norun &
				#decrease time and print back to file
				time=$(awk '{print($1-1)}' ~/.config/scripts/allowlist/totaltime)
				echo "$time" > ~/.config/scripts/allowlist/totaltime
				#notify-send "time is $time"
				sleep 1
			done
			#restore wallpaper and Xresources
			mv -f /home/blink/.config/wall.png /home/blink/.config/wallpaper/wall_Deep.png
			cp -f /home/blink/.config/wallpaper/wall_Shallow.png /home/blink/.config/wall.png
			rm -f /home/blink/.config/wall_Deep.png
			rm -f /home/blink/.config/scripts/isfocusing
			#set all whitelist values back to 0
			xrdb /home/blink/.config/Xresources &&
			i3-msg restart &&
			sleep 1 #so Xresources can refresh before setting xst back
			pkill -x --signal USR1 xst
			setbg
		fi
	fi
	notify-send "Thank you for focusing on your work!"
fi
