#!/usr/bin/env sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
xcompmgr &		# xcompmgr for transparency
$STATUSBAR &		# script for updating the status bar
dunst &			# dunst for notifications
sxhkd &			# Bind keys with sxhkd
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
mpd-module-update &	# Check for when to update the mpd module


xsetwacom -v set "Wacom One by Wacom S Pen stylus" 'MapToOutput' 1920X1080+0+0 &
xsetwacom set "Wacom One by Wacom S Pen stylus" Button 2 "key +super +ctrl z -super -ctrl" &
xsetwacom set "Wacom One by Wacom S Pen stylus" Button 3 "key +super +shift z -super -shift" &
nvidia-settings --assign CurrentMetaMode="DPY-0: nvidia-auto-select +0+0 {ForceCompositionPipeline=On}, DPY-1: nvidia-auto-select +1920+0 {ForceCompositionPipeline=On}"

