#!/bin/bash
time=$(echo -e "How many minutes do you want to focus for?" | dmenu -i)
if [[ $time -eq allow ]]
then
	allowedprogram=$(echo -e "choose program to allow" | dmenu -i)
	allowedtime=$(echo -e "how many minutes?" | dmenu -i)
	let allowedtime=allowedtime\*60
	echo "$allowedtime" > ~/.config/scripts/allowlist/$allowedprogram
else
	resource=$(echo -e "Blaze\nCosmo\nCelestia\nChurch\nMario\nPooh\nShip\nStella" | dmenu -i)
	#echo -e "time set for $time minutes!"
	#let time=time\*60
	if [ $time -gt 0 ]
	then
		#set wallpaper and Xresources
		mv -f /home/blink/.config/wall.png /home/blink/.config/wallpaper/wall_Shallow.png
		cp -f /home/blink/.config/wallpaper/wall_$resource.png /home/blink/.config/wall.png
		setbg &&
		xrdb /home/blink/.config/Xassets/X$resource &&
		pkill -x --signal USR1 xst &&
		i3-msg restart &
		sleep 1 #so Xresources can refresh before booting up orgterm
		#start up orgterm if nothing is playing currently
		if mpc status | grep playing
		then
			notify-send "mpd is playing, enjoy your current music"
		else
			orgtermrun=$(pgrep -cx orgterm)
			if orgtermrun -gt 0
			then
				st orgterm ~/King\ Of\ A\ Cursed\ Throne.org
			fi
		fi
		#sleep and check for unallowed programs
		while [[ $time -gt 0 ]]
		do
			~/.config/scripts/norun &
			time=$((time-1))
			#notify-send "time is $time"
			sleep 1
		done
		#restore wallpaper and Xresources
		mv -f /home/blink/.config/wall.png /home/blink/.config/wallpaper/wall_Deep.png
		cp -f /home/blink/.config/wallpaper/wall_Shallow.png /home/blink/.config/wall.png
		rm -f /home/blink/.config/wall_Deep.png
		#set all whitelist values back to 0
		xrdb /home/blink/.config/Xresources ;
		i3-msg restart &
		pkill -x --signal USR1 xst
		setbg
	fi
	notify-send "Thank you for focusing on your work!"
fi
