#!/bin/bash
FILES=~/.config/scripts/allowlist/*

for Program in $FILES
do
	Program=$(echo $Program | sed "s/.*\///")
	num=$(awk '{print($1)}' $FILES$Program)
	#notify-send "Program is $Program"
	if [[ $num -le 0 ]]
	then
		if [[ $num -gt -2 ]]
		then
			pgrep -cx $Program && pkill $Program &&
			notify-send "Whoops you're not allowed to run $Program right now!"
		fi
	else
		let num-=1;
		echo "$num" > $FILES$Program
		#notify-send "$Program time is $num"
	fi
done
